//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefreshWeatherData.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenWeatherMapApiKey {
            get {
                return ((string)(this["OpenWeatherMapApiKey"]));
            }
            set {
                this["OpenWeatherMapApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fussen")]
        public string OpenWeatherMapLocationName {
            get {
                return ((string)(this["OpenWeatherMapLocationName"]));
            }
            set {
                this["OpenWeatherMapLocationName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.99.14")]
        public string PlcIpAddress {
            get {
                return ((string)(this["PlcIpAddress"]));
            }
            set {
                this["PlcIpAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PlcRack {
            get {
                return ((int)(this["PlcRack"]));
            }
            set {
                this["PlcRack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int PlcSlot {
            get {
                return ((int)(this["PlcSlot"]));
            }
            set {
                this["PlcSlot"] = value;
            }
        }
        
        /// <summary>
        /// The S7 Address of the value. Can be any valid S7 identifier, such as DB123.DBD0. Must be an value of type &quot;Real&quot;.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The S7 Address of the value. Can be any valid S7 identifier, such as DB123.DBD0. " +
            "Must be an value of type \"Real\".")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MD1000")]
        public string TemperaturaAddress {
            get {
                return ((string)(this["TemperaturaAddress"]));
            }
            set {
                this["TemperaturaAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MD1004")]
        public string PressureAddress {
            get {
                return ((string)(this["PressureAddress"]));
            }
            set {
                this["PressureAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MD1008")]
        public string HumidityAddress {
            get {
                return ((string)(this["HumidityAddress"]));
            }
            set {
                this["HumidityAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MD1012")]
        public string WindSpeedAddress {
            get {
                return ((string)(this["WindSpeedAddress"]));
            }
            set {
                this["WindSpeedAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MD1016")]
        public string WindDirectionAddress {
            get {
                return ((string)(this["WindDirectionAddress"]));
            }
            set {
                this["WindDirectionAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MD1020")]
        public string CloudPercentAddress {
            get {
                return ((string)(this["CloudPercentAddress"]));
            }
            set {
                this["CloudPercentAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MD1024")]
        public string LocationNameAddress {
            get {
                return ((string)(this["LocationNameAddress"]));
            }
            set {
                this["LocationNameAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int LocationNameStringLength {
            get {
                return ((int)(this["LocationNameStringLength"]));
            }
            set {
                this["LocationNameStringLength"] = value;
            }
        }
    }
}
